---
- name: path.local_bin | ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: path.local_bin | ensure PATH includes ~/.local/bin
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.SHELL | regex_search('zsh') | ternary(ansible_user_dir + '/.zshrc', ansible_user_dir + '/.bashrc') }}"
    regexp: '^(export\s+PATH=.+)?\$HOME/.local/bin:\$PATH'
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
    create: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"