---
- name: path.local_bin | ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.local/bin
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: path.local_bin | ensure PATH includes ~/.local/bin
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.SHELL | regex_search('zsh') | ternary('/home/' + ansible_user + '/.zshrc', '/home/' + ansible_user + '/.bashrc') }}"
    regexp: '^(export\s+PATH=.+)?\$HOME/.local/bin:\$PATH'
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
    create: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"